name: Ready for docs-content review

# **What it does**: Adds pull requests in the docs-internal repository to the docs-content review board when the "ready-for-doc-review" label is added or when a review by docs-content or docs-reviewers is requested. This workflow is also called as a reusable workflow from other repos including docs-content, docs-strategy, docs-early-access, and github.
# **Why we have it**: So that other GitHub teams can easily request reviews from the docs-content team, and so that writers can see when a PR is ready for review
# **Who does it impact**: Writers who need to review docs-related PRs

on:
  pull_request:
    types: [labeled, review_requested]
  workflow_call:

permissions:
  contents: read

jobs:
  request_doc_review:
    name: Request a review from the docs-content team
    if: >-
      github.repository_owner == 'github' && github.repository != 'github/docs' &&
      (github.event.label.name == 'ready-for-doc-review' || github.event.requested_team.name == 'docs-content' || github.event.requested_team.name == 'docs-reviewers')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo content
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          repository: github/docs-internal
          token: ${{ secrets.DOCS_BOT_PAT_WRITEORG_PROJECT }}

      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version-file: 'package.json'
          cache: npm

      - name: Install dependencies
        run: npm install @octokit/graphql

      - name: Set AUTHOR_LOGIN
        run: |
          if [[ "${{ github.event.pull_request.assignee.login && github.event.pull_request.user.login == 'docs-bot' }}" ]]; then
            echo "AUTHOR_LOGIN=${{ github.event.pull_request.assignee.login }}" >> $GITHUB_ENV
          else
            echo "AUTHOR_LOGIN=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
          fi

      - name: Run script
        run: |
          node src/workflows/ready-for-docs-review.js
        env:
          TOKEN: ${{ secrets.DOCS_BOT_PAT_WRITEORG_PROJECT }}
          PROJECT_NUMBER: 2936
          ORGANIZATION: 'github'
          ITEM_NODE_ID: ${{ github.event.pull_request.node_id }}
          REPO: ${{ github.event.pull_request.base.repo.full_name }}

        # Since the projects API is still in beta, use the old workflow if something fails
        # so that we don't miss these PRs
      - name: Backup action (Add pull request to FR project board)
        if: ${{ failure() }}
        uses: rachmari/actions-add-new-issue-to-column@1a459ef92308ba7c9c9dc2fcdd72f232495574a9
        with:
          action-token: ${{ secrets.DOCS_BOT_PAT_WORKFLOW_READORG }}
          project-url: 'https://github.com/orgs/github/projects/1367'
          column-name: 'Docs-internal external contributor PRs'
